#!/usr/bin/env node
// 운영 Supabase 스키마(데이터 제외)를 카탈로그 SELECT 로 뽑아 이 폴더의 00~07 SQL 과 counts.json 을 다시 쓴다.
//   node supabase/schema/dump.mjs            (Aside 브라우저에 Supabase 대시보드가 로그인돼 있어야 함)
// 토큰·접속 문자열은 pgmeta.mjs 가 브라우저 탭 안에서만 쓰며 어디에도 저장하지 않는다. SELECT 만 부른다.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { pgmeta, REF } from './pgmeta.mjs';

const DIR = path.dirname(fileURLToPath(import.meta.url));
const APP = `n.nspname = 'public'`; // 앱 스키마(확인 결과 public 하나뿐)
const rel = (c) => `format('%I.%I', ${c}n.nspname, ${c}c.relname)`;

// ---- 쿼리 정의 (모두 SELECT) ----
const Q = {
  ext: `select extname, (select nspname from pg_namespace where oid=extnamespace) sch from pg_extension order by extname`,
  enums: `select format('create type %I.%I as enum (%s);', n.nspname, t.typname,
      (select string_agg(quote_literal(enumlabel), ', ' order by enumsortorder) from pg_enum e where e.enumtypid=t.oid)) sql
    from pg_type t join pg_namespace n on n.oid=t.typnamespace where ${APP} and t.typtype='e' order by t.typname`,
  domains: `select format('create domain %I.%I as %s%s%s;', n.nspname, t.typname, format_type(t.typbasetype,t.typtypmod),
      case when t.typdefault is not null then ' default '||t.typdefault else '' end,
      case when t.typnotnull then ' not null' else '' end) sql
    from pg_type t join pg_namespace n on n.oid=t.typnamespace where ${APP} and t.typtype='d' order by t.typname`,
  composites: `select format('create type %I.%I as (%s);', n.nspname, t.typname,
      (select string_agg(format('%I %s', a.attname, format_type(a.atttypid,a.atttypmod)), ', ' order by a.attnum) from pg_attribute a where a.attrelid=t.typrelid and a.attnum>0 and not a.attisdropped)) sql
    from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_class c on c.oid=t.typrelid
    where ${APP} and t.typtype='c' and c.relkind='c' order by t.typname`,
  // 독립 시퀀스(컬럼 소유 아님·identity 아님)
  seqs: `select format('create sequence %I.%I as %s start with %s increment by %s minvalue %s maxvalue %s cache %s %scycle;',
      n.nspname, c.relname, format_type(s.seqtypid,null), s.seqstart, s.seqincrement, s.seqmin, s.seqmax, s.seqcache, case when s.seqcycle then '' else 'no ' end) sql
    from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_sequence s on s.seqrelid=c.oid
    where ${APP} and c.relkind='S' and not exists (select 1 from pg_depend d where d.objid=c.oid and d.deptype='i') order by c.relname`,
  seqown: `select format('alter sequence %I.%I owned by %I.%I.%I;', n.nspname, c.relname, n.nspname, t.relname, a.attname) sql
    from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_depend d on d.objid=c.oid and d.deptype='a'
    join pg_class t on t.oid=d.refobjid join pg_attribute a on a.attrelid=t.oid and a.attnum=d.refobjsubid
    where ${APP} and c.relkind='S' order by c.relname`,
  tables: `select c.oid::int oid, format('%I.%I', n.nspname, c.relname) name, c.relkind, c.relispartition,
      (select string_agg(format('  %I %s%s%s%s', a.attname, format_type(a.atttypid,a.atttypmod),
         case when a.attidentity='a' then ' generated always as identity' when a.attidentity='d' then ' generated by default as identity' else '' end,
         case when a.attgenerated='s' then ' generated always as ('||pg_get_expr(ad.adbin,ad.adrelid)||') stored'
              when ad.adbin is not null and a.attidentity='' then ' default '||pg_get_expr(ad.adbin,ad.adrelid) else '' end,
         case when a.attnotnull then ' not null' else '' end), E',\\n' order by a.attnum)
       from pg_attribute a left join pg_attrdef ad on ad.adrelid=a.attrelid and ad.adnum=a.attnum
       where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped) cols
    from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('r','p') order by c.relname`,
  comments: `select format('comment on %s %s is %s;', case when c.relkind in ('r','p') then 'table' when c.relkind='v' then 'view' else 'materialized view' end, ${rel('')}, quote_literal(d.description)) sql
    from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_description d on d.objoid=c.oid and d.objsubid=0 and d.classoid='pg_class'::regclass
    where ${APP} and c.relkind in ('r','p','v','m')
    union all
    select format('comment on column %I.%I.%I is %s;', n.nspname, c.relname, a.attname, quote_literal(d.description))
    from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_description d on d.objoid=c.oid and d.objsubid>0 and d.classoid='pg_class'::regclass
    join pg_attribute a on a.attrelid=c.oid and a.attnum=d.objsubid where ${APP} and c.relkind in ('r','p','v','m')
    order by 1`,
  // 제약: PK/UNIQUE/CHECK/EXCLUDE 먼저, FK 는 뒤에
  cons: `select (con.contype='f') is_fk, format('alter table %s add constraint %I %s;', format('%I.%I', n.nspname, c.relname), con.conname, pg_get_constraintdef(con.oid)) sql
    from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace
    where ${APP} and con.contype in ('p','u','c','x','f') order by is_fk, c.relname, con.contype, con.conname`,
  idx: `select pg_get_indexdef(i.indexrelid)||';' sql
    from pg_index i join pg_class ic on ic.oid=i.indexrelid join pg_class c on c.oid=i.indrelid join pg_namespace n on n.oid=c.relnamespace
    where ${APP} and c.relkind in ('r','p') and not exists (select 1 from pg_constraint k where k.conindid=i.indexrelid and k.contype in ('p','u','x'))
    order by c.relname, ic.relname`,
  funcs: `select pg_get_functiondef(p.oid) sql, format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) sig
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where ${APP} and p.prokind in ('f','p') and not exists (select 1 from pg_depend d where d.objid=p.oid and d.deptype='e')
    order by p.proname, pg_get_function_identity_arguments(p.oid)`,
  fcomments: `select format('comment on %s %I.%I(%s) is %s;', case when p.prokind='p' then 'procedure' else 'function' end, n.nspname, p.proname, pg_get_function_identity_arguments(p.oid), quote_literal(d.description)) sql
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_description d on d.objoid=p.oid and d.classoid='pg_proc'::regclass and d.objsubid=0
    where ${APP} and p.prokind in ('f','p') order by 1`,
  views: `select format('create or replace view %I.%I%s as%s%s', n.nspname, c.relname,
      case when c.reloptions is not null then ' with ('||array_to_string(c.reloptions, ', ')||')' else '' end, E'\\n', pg_get_viewdef(c.oid, true)) sql
    from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('v','m') order by c.relname`,
  // 앱 테이블 트리거 + auth/storage/realtime 에 건 우리 트리거(함수가 앱 스키마)
  trg: `select n.nspname sch, pg_get_triggerdef(t.oid, true)||';' sql
    from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid join pg_namespace pn on pn.oid=p.pronamespace
    where not t.tgisinternal and (${APP} or pn.nspname='public') order by n.nspname, c.relname, t.tgname`,
  evtrg: `select count(*) n from pg_event_trigger e join pg_proc p on p.oid=e.evtfoid join pg_namespace pn on pn.oid=p.pronamespace where pn.nspname='public'`,
  rls: `select format('alter table %I.%I enable row level security;', n.nspname, c.relname)||case when c.relforcerowsecurity then format(E'\\nalter table %I.%I force row level security;', n.nspname, c.relname) else '' end sql
    from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('r','p') and c.relrowsecurity order by c.relname`,
  rlsoff: `select format('%I.%I', n.nspname, c.relname) name from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('r','p') and not c.relrowsecurity order by 1`,
  pol: `select schemaname sch, format('create policy %I on %I.%I as %s for %s%s%s%s;', policyname, schemaname, tablename, permissive, cmd,
      case when roles = '{public}' then '' else ' to '||array_to_string(roles, ', ') end,
      case when qual is not null then E'\\n  using ('||qual||')' else '' end,
      case when with_check is not null then E'\\n  with check ('||with_check||')' else '' end) sql
    from pg_policies where schemaname in ('public','storage') order by schemaname, tablename, policyname`,
  // GRANT: 앱 스키마의 테이블·시퀀스·함수 ACL 을 객체별로 (소유자 postgres 제외)
  acl: `with o as (
      select 'table' kind, format('%I.%I', n.nspname, c.relname) name, c.relacl acl, c.relname ord from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('r','p','v','m')
      union all select 'sequence', format('%I.%I', n.nspname, c.relname), c.relacl, c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind='S'
      union all select case when p.prokind='p' then 'procedure' else 'function' end, format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)), p.proacl, p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where ${APP} and p.prokind in ('f','p') and not exists (select 1 from pg_depend d where d.objid=p.oid and d.deptype='e')
    ), g as (
      select kind, name, ord, case when x.grantee=0 then 'public' else x.grantee::regrole::text end grantee,
        string_agg(case x.privilege_type when 'SELECT' then 'select' when 'INSERT' then 'insert' when 'UPDATE' then 'update' when 'DELETE' then 'delete'
          when 'TRUNCATE' then 'truncate' when 'REFERENCES' then 'references' when 'TRIGGER' then 'trigger' when 'MAINTAIN' then 'maintain'
          when 'USAGE' then 'usage' when 'EXECUTE' then 'execute' end, ', ' order by x.privilege_type) privs
      from o, lateral aclexplode(o.acl) x where o.acl is not null and x.grantee <> (select oid from pg_roles where rolname='postgres') group by 1,2,3,4
    )
    select kind, name, ord, grantee, privs from g order by kind, ord, name, grantee`,
  noacl: `select kind, name from (
      select 'table' kind, format('%I.%I', n.nspname, c.relname) name from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('r','p','v','m') and c.relacl is null
      union all select 'function', format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where ${APP} and p.prokind in ('f','p') and p.proacl is null) z order by 1,2`,
  schemaacl: `select nspname, nspacl::text acl from pg_namespace where nspname='public'`,
  defacl: `select defaclrole::regrole::text role, coalesce(defaclnamespace::regnamespace::text,'') sch, defaclobjtype typ, defaclacl::text acl from pg_default_acl where defaclnamespace=0 or defaclnamespace::regnamespace::text='public' order by 1,2,3`,
  buckets: `select id, name, public, file_size_limit, allowed_mime_types from storage.buckets order by id`,
  pubs: `select p.pubname, p.pubinsert, p.pubupdate, p.pubdelete, p.pubtruncate, pt.schemaname, pt.tablename, pt.rowfilter
    from pg_publication p left join pg_publication_tables pt on pt.pubname=p.pubname where p.pubname='supabase_realtime' order by pt.tablename`,
  // 운영 객체 수 (README 대조표)
  counts: `select
      (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('r','p'))::int tables,
      (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where ${APP} and p.prokind in ('f','p'))::int functions,
      (select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and ${APP})::int triggers_public,
      (select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid join pg_namespace pn on pn.oid=p.pronamespace where not t.tgisinternal and not (${APP}) and pn.nspname='public')::int triggers_other_schema,
      (select count(*) from pg_policies where schemaname='public')::int policies_public,
      (select count(*) from pg_policies where schemaname='storage')::int policies_storage,
      (select count(*) from pg_indexes where schemaname='public')::int indexes,
      (select count(*) from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where ${APP} and con.contype in ('p','u','c','x','f'))::int constraints,
      (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind='S')::int sequences,
      (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('v','m'))::int views,
      (select count(*) from pg_type t join pg_namespace n on n.oid=t.typnamespace where ${APP} and t.typtype in ('e','d') )::int types,
      (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where ${APP} and c.relkind in ('r','p') and c.relrowsecurity)::int rls_tables,
      (select count(*) from storage.buckets)::int buckets,
      (select count(*) from pg_publication_tables where pubname='supabase_realtime')::int realtime_tables`,
};

const keys = Object.keys(Q);
const res = Object.fromEntries(pgmeta(keys.map((k) => Q[k])).map((r, i) => [keys[i], r]));

// ---- 파일 만들기 ----
const head = (title) => `-- ${title}\n-- LivePulse 운영 DB(${REF}) 스키마 덤프 — 자동 생성(supabase/schema/dump.mjs). 직접 고치지 말고 다시 덤프한다.\n-- 데이터는 없음(storage.buckets 메타 행 제외).\n\n`;
const lines = (rows, f = (r) => r.sql) => rows.map(f).join('\n');
const out = {};

// 00 확장
{
  const skip = new Set(['plpgsql', 'pg_stat_statements', 'supabase_vault']); // 플랫폼 기본 제공
  let s = head('00 확장') + 'create schema if not exists public;\ncreate schema if not exists extensions;\n\n';
  for (const e of res.ext) {
    s += skip.has(e.extname) ? `-- ${e.extname} (스키마 ${e.sch}): Supabase 플랫폼 기본 제공 — 생성하지 않음\n`
      : `create extension if not exists ${JSON.stringify(e.extname)} with schema ${e.sch};\n`;
  }
  out['00_extensions.sql'] = s;
}
// 01 타입
out['01_types.sql'] = head('01 사용자 타입·enum') + [...res.enums, ...res.domains, ...res.composites].map((r) => r.sql).join('\n') + '\n' +
  (res.enums.length + res.domains.length + res.composites.length === 0 ? '-- (없음)\n' : '');
// 02 테이블
{
  let s = head('02 시퀀스·테이블(컬럼·기본값·NOT NULL·identity)');
  if (res.seqs.length) s += lines(res.seqs) + '\n\n';
  for (const t of res.tables) s += `create table ${t.name} (\n${t.cols}\n);\n\n`;
  if (res.seqown.length) s += lines(res.seqown) + '\n\n';
  if (res.comments.length) s += lines(res.comments) + '\n';
  out['02_tables.sql'] = s;
}
// 03 제약·인덱스
out['03_constraints_indexes.sql'] = head('03 제약(PK·UNIQUE·CHECK 먼저, FK 나중)·인덱스') +
  lines(res.cons) + '\n\n' + lines(res.idx) + '\n';
// 04 함수
{
  let s = head('04 함수·프로시저 전부(aggregate 제외)') + 'set check_function_bodies = false;\n\n';
  s += res.funcs.map((f) => f.sql.trim().replace(/;?$/, ';')).join('\n\n') + '\n';
  if (res.fcomments.length) s += '\n' + lines(res.fcomments) + '\n';
  out['04_functions.sql'] = s;
}
// 05 뷰·트리거
{
  let s = head('05 뷰·트리거');
  s += res.views.length ? res.views.map((v) => v.sql.trim().replace(/;?$/, ';')).join('\n\n') + '\n\n' : '-- 뷰 없음\n\n';
  s += '-- 앱 테이블 트리거\n' + lines(res.trg.filter((t) => t.sch === 'public')) + '\n';
  out['05_views_triggers.sql'] = s;
}
// 06 RLS·정책·GRANT
{
  let s = head('06 RLS·정책·GRANT');
  s += '-- RLS 켜기\n' + lines(res.rls) + '\n';
  if (res.rlsoff.length) s += '-- RLS 꺼진 테이블(운영 그대로): ' + res.rlsoff.map((r) => r.name).join(', ') + '\n';
  s += '\n-- 정책(public)\n' + lines(res.pol.filter((p) => p.sch === 'public')) + '\n';
  s += '\n-- GRANT: 운영 ACL 그대로. 객체별로 anon/authenticated/service_role/public 기본 권한을 먼저 걷어내고 운영 값만 준다.\n';
  s += '-- (소유자 postgres 의 권한은 소유자라 항상 있어 적지 않음)\n';
  s += `-- public 스키마 ACL(운영): ${res.schemaacl[0]?.acl}\n`;
  const byObj = new Map();
  for (const a of res.acl) { const k = a.kind + '|' + a.name; if (!byObj.has(k)) byObj.set(k, { kind: a.kind, name: a.name, g: [] }); byObj.get(k).g.push(a); }
  const noacl = new Set(res.noacl.map((a) => a.kind + '|' + a.name));
  const all = new Map([...byObj]);
  for (const k of noacl) if (!all.has(k)) { const [kind, ...n] = k.split('|'); all.set(k, { kind, name: n.join('|'), g: [] }); }
  const order = { table: 0, sequence: 1, function: 2, procedure: 3 };
  const objs = [...all.values()].sort((a, b) => order[a.kind] - order[b.kind] || a.name.localeCompare(b.name));
  for (const o of objs) {
    const hasAcl = !noacl.has(o.kind + '|' + o.name);
    if (!hasAcl) continue; // acl null = 기본 권한 그대로(재현 시에도 기본)
    s += `revoke all on ${o.kind} ${o.name} from public, anon, authenticated, service_role;\n`;
    for (const g of o.g) s += `grant ${g.privs} on ${o.kind} ${o.name} to ${g.grantee};\n`;
  }
  s += '\n-- 기본 권한(운영 pg_default_acl, 참고용 — Supabase 가 프로젝트 생성 때 기본으로 걸어 주므로 적용하지 않음)\n';
  for (const d of res.defacl) s += `--   role=${d.role} schema=${d.sch || '(전체)'} type=${d.typ} acl=${d.acl}\n`;
  out['06_rls_policies_grants.sql'] = s;
}
// 07 storage·realtime·auth 트리거
{
  let s = head('07 storage 버킷·storage.objects 정책·realtime·auth 트리거');
  s += '-- auth 스키마 등 앱 밖 테이블에 건 우리 트리거(함수는 04 에 있음)\n';
  const other = res.trg.filter((t) => t.sch !== 'public');
  s += other.length ? lines(other) + '\n' : '-- (없음)\n';
  s += '\n-- storage 버킷(메타 행만: 이름·public 여부, 있으면 크기·MIME 제한)\n';
  for (const b of res.buckets) {
    s += `insert into storage.buckets (id, name, public${b.file_size_limit != null ? ', file_size_limit' : ''}${b.allowed_mime_types ? ', allowed_mime_types' : ''}) values (${[
      `'${b.id}'`, `'${b.name}'`, b.public, ...(b.file_size_limit != null ? [b.file_size_limit] : []),
      ...(b.allowed_mime_types ? [`array[${b.allowed_mime_types.map((m) => `'${m}'`).join(', ')}]`] : [])].join(', ')})\n` +
      `  on conflict (id) do update set public = excluded.public${b.file_size_limit != null ? ', file_size_limit = excluded.file_size_limit' : ''}${b.allowed_mime_types ? ', allowed_mime_types = excluded.allowed_mime_types' : ''};\n`;
  }
  s += '\n-- storage.objects 정책\n' + lines(res.pol.filter((p) => p.sch === 'storage')) + '\n';
  s += '\n-- realtime publication supabase_realtime\n';
  const tabs = res.pubs.filter((p) => p.tablename);
  const rf = tabs.filter((p) => p.rowfilter);
  s += tabs.map((p) => `alter publication supabase_realtime add table ${p.schemaname}.${p.tablename};`).join('\n') + '\n';
  if (rf.length) s += `-- 주의: 행 필터가 걸린 테이블 ${rf.length}개는 수동 확인 필요\n`;
  out['07_storage_realtime.sql'] = s;
}

for (const [f, c] of Object.entries(out)) fs.writeFileSync(path.join(DIR, f), f.startsWith('04_') ? c : c.replace(/\n{3,}/g, '\n\n'));
const counts = { ...res.counts[0], event_triggers_public_fn: res.evtrg[0].n };
fs.writeFileSync(path.join(DIR, 'counts.json'), JSON.stringify({ dumpedAt: new Date().toISOString().slice(0, 10), ref: REF, prod: counts, dumpedFunctions: res.funcs.length }, null, 2) + '\n');
console.log(JSON.stringify(counts));
console.log('쓴 파일:', Object.keys(out).join(', '), '+ counts.json');
