-- ============================================================
-- 022: 디자인 검증 강화 (에디터 검증 라운드 반영)
-- ① sp_live_design_q: status IN ('published','active','ended') — 종료 화면
--    브랜드 토큰 유지 (E0 원칙)
-- ② sp_partner_design_s (save_draft/publish 검증 확장):
--    - 전 장면(scenes.*) 섹션 수 ≤12
--    - settings.link 필드는 ^https?:// 만 허용 (저장형 XSS 스킴 차단,
--      렌더러 safeUrl과 이중 방어)
--    - scenes.enter 필수 + joinCard 정확히 1개(숨김 불가) — 누락 우회 봉쇄
-- (원격 적용 완료 — MCP apply_migration, 2026-07-12. 전문은 원격 DB 원본,
--  함수 골격은 020과 동일 + 위 검증 블록 추가)
-- ============================================================
